### ISSUE TITLE
NullReferenceException when stopping

### ISSUE THREAD

**Issue by massada** [Farfetch/kafka-flow#256]
A `NullReferenceException` is being thrown in `WorkerPoolFeeder` when stopping the framework. This is because we're not awaiting for the background task to stop after cancelling the token.

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at KafkaFlow.Consumers.ConsumerWorkerPool.EnqueueAsync(ConsumeResult`2 message, CancellationToken stopCancellationToken)
   at KafkaFlow.Consumers.WorkerPoolFeeder.<>c__DisplayClass6_0.<<Start>b__0>d.MoveNext()
```

**Comment by SonicGD** [comment]
Hello. Same issue in our applications:

```
   at KafkaFlow.Consumers.ConsumerWorkerPool.<EnqueueAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at KafkaFlow.Consumers.WorkerPoolFeeder.<>c__DisplayClass6_0.<<Start>b__0>d.MoveNext()
```
